branches: {only: [master, test]}
cache:
  - '%LocalAppData%\pip\cache'
environment:
  matrix:
    - TOXENV: py37-pipmaster
    - TOXENV: py37-pip190
    - TOXENV: py37-pip181
    - TOXENV: py37-pip10
    - TOXENV: py36-pipmaster
    - TOXENV: py36-pip190
    - TOXENV: py36-pip180
    - TOXENV: py36-pip10
    - TOXENV: py36-pip9
    - TOXENV: py35-pip9
    - TOXENV: py34-pip9
    - TOXENV: py34-pip8
    - TOXENV: py27-pip190
    - TOXENV: py27-pip181
    - TOXENV: py27-pip10
    - TOXENV: py27-pip9
    - TOXENV: py27-pip8
install:
  - pip install tox==3.7.0
build: false
test_script:
  - tox -v
after_test:
  - pip install codecov
  - codecov
