branches: {only: [master]}

dist: xenial
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"

env:
  - PIP=8.1.1
  - PIP=9.0.1
  - PIP=9.0.3
  - PIP=10.0.1
  - PIP=18.0
  - PIP=19.0
  - PIP=latest
  - PIP=master

cache: pip
install:
  - travis_retry pip install tox-travis codecov coveralls
script:
  - tox
after_success:
  - codecov -e PIP
  - "COVERALLS_PARALLEL=true coveralls"

jobs:
  exclude:
    - python: "pypy3.5-6.0"
      env: PIP=8.1.1
  include:
    - stage: flake8
      python: 2.7
      env: TOXENV=flake8
      after_success: skip  # No need coverage
    - stage: readme
      python: 2.7
      env: TOXENV=readme
      after_success: skip  # No need coverage
  allow_failures:
    - env: PIP=master

notifications:
  webhooks: https://coveralls.io/webhook
