branches: {only: [master, test]}

sudo: false
language: python
cache: pip

matrix:
  include:
    - name: Style
      env: TOXENV=style
      python: "3.6"

    - name: Packaging
      env: TOXENV=packaging
      python: "3.6"

    - name: Requirements
      env: TOXENV=requirements
      python: "3.6"

    - name: PyPy2.7
      python: "pypy2.7-6.0"
      dist: xenial

    - name: PyPy3.5
      python: "pypy3.5-6.0"
      dist: xenial

    - name: Python 3.7
      python: "3.7"
      dist: xenial

    - name: Python 3.6
      python: "3.6"

    - name: Python 3.5
      python: "3.5"

    - name: Python 3.4
      python: "3.4"

    - name: Python 2.7
      python: "2.7"

install:
  - pip install tox==3.7.0 tox-travis==0.11
  - pip install -U setuptools
  - python setup.py sdist

script: tox -v --installpkg dist/*.tar.gz

after_success:
  - pip install codecov
  - codecov -e TRAVIS_PYTHON_VERSION
