branches: {only: [master]}

sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

env:
  - PIP=8.1.1
  - PIP=9.0.1
  - PIP=9.0.3
  - PIP=10.0.1
  - PIP=18.0
  - PIP=19.0
  - PIP=latest
  - PIP=master
  - PIP=latest

cache: pip
install:
  - travis_retry pip install tox-travis
script:
  - tox

jobs:
  include:
    - stage: flake8
      python: 2.7
      env: TOXENV=flake8
    - stage: readme
      python: 2.7
      env: TOXENV=readme
